-- AlterEnum
ALTER TYPE "CandleTimeframe" ADD VALUE IF NOT EXISTS 'M30';
ALTER TYPE "CandleTimeframe" ADD VALUE IF NOT EXISTS 'H4';
ALTER TYPE "CandleTimeframe" ADD VALUE IF NOT EXISTS 'D1';
ALTER TYPE "CandleTimeframe" ADD VALUE IF NOT EXISTS 'W1';
ALTER TYPE "CandleTimeframe" ADD VALUE IF NOT EXISTS 'MN1';
ALTER TYPE "CandleTimeframe" ADD VALUE IF NOT EXISTS 'Y1';
